version: "3"
services:
  task_template:
    build:
      context: ./task_template
      dockerfile: ${TASK_DOCKERFILE}
    networks:
      - mynetwork
  model_template:
    build: ./model_template
    networks:
      - mynetwork
    environment:
      - MODEL_TO_USE=${MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  model_handler_template:
    build: ./model_handler_template
    networks:
      - mynetwork
    environment:
      - ATLAS_URI=mongodb://collabai-mongo/
  orchestrator:
    depends_on:
      - task_template
      - model_template
      - model_handler_template
    build: ./orchestrator
    networks:
      - mynetwork
  mongo:
    container_name: collabai-mongo
    image: mongo:7.0.4
    volumes:
      - ./mongodb:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - mynetwork
  nginx:
    image: docker.io/library/nginx:alpine
    environment:
      - HOSTNAME=localhost
    ports:
      - 0.0.0.0:${NGINX_HTTPS_PORT}:443
    volumes:
      - ./dev_data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dev_data/nginx/templates:/etc/nginx/templates
      - ./dev_data/certs/sp.crt:/certificates/certificate.crt
      - ./dev_data/certs/sp.key:/certificates/private.key
    depends_on:
      - task_template
    container_name: nginx-server
    networks:
      - mynetwork
networks:
  mynetwork:
